[workdir]
workdir_ = ./
[parallel]
thread_num = 1
[Mesh]
L = 256
Cell_Len = 1.0
BlockCellLen = 64
[Phase_Field]
W = 4.0
M = 0.01
[Two_Phase]
rho_l = 1.0
rho_h = 1.975
eta_l = 0.0073
eta_h = 0.292
sigma = 0.0071
[Magnetic_Field]
mu_l = 1.0
mu_h = 2.2
chi_l = 0.0
chi_h = 1.2
; H0/Hc = 0, 1.04, 1.74 correspond to the paper's 0, 4.9, 8.2 kA/m cases.
H0_over_Hc = 1.74
PsiSolver_Iter = 100
PsiSolver_K = 0.5
PsiSolver_Residual = 1.0e-8
[Simulation_Settings]
TotalStep = 12000
OutputStep = 1000
